# Generated by Django 5.2.7 on 2025-10-28 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cancion",
            fields=[
                ("id_cancion", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=200)),
                ("artista", models.CharField(max_length=150)),
                ("archivo", models.FileField(upload_to="musica/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_subidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canciones",
                        to="biblioteca.genero",
                    ),
                ),
            ],
        ),
    ]
